# -*- coding: utf-8 -*-
"""data_preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXom_QGfXjdgBr79VOp7Tp9_Eo37JuE0
"""

# src/data_preprocessing.py

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

def preprocess_data(filepath):
    # Load dataset
    data = pd.read_csv(filepath)

    # Handle missing values
    data = data.dropna(subset=['drug1', 'drug2', 'interaction_type'])

    # Encode drug names to IDs
    drug_encoder = LabelEncoder()
    all_drugs = pd.concat([data['drug1'], data['drug2']]).unique()
    drug_encoder.fit(all_drugs)

    data['drug1_id'] = drug_encoder.transform(data['drug1'])
    data['drug2_id'] = drug_encoder.transform(data['drug2'])

    # Encode interaction types
    interaction_encoder = OneHotEncoder(sparse_output=False)
    interaction_types = interaction_encoder.fit_transform(data[['interaction_type']])

    return data, drug_encoder, interaction_encoder, interaction_types